name: immich

services:
  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    container_name: immich_postgres
    volumes:
      - ${APPS_FOLDER}/immich/db:/var/lib/postgresql/data
    environment:
      TZ: Europe/Berlin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    networks:
      immich:
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    shm_size: 128mb

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v2.4.1@sha256:b3deefd1826f113824e9d7bc30d905e7f823535887d03f869330946b6db3b44a
    container_name: immich_machine_learning
    volumes:
      - model-cache:/cache
    environment:
      TZ: Europe/Berlin
    networks:
      immich:
    restart: unless-stopped
    user: 568:568
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

  immich-server:
    image: ghcr.io/immich-app/immich-server:v2.4.1@sha256:e6a6298e67ae077808fdb7d8d5565955f60b0708191576143fc02d30ab1389d1
    container_name: immich_server
    depends_on:
      - database
      - redis
    volumes:
      - ${CONTENT_FOLDER}/images:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Europe/Berlin
      IMMICH_TRUSTED_PROXIES: 172.31.255.0/24,fdd0:0:0:1000::/64
    env_file:
      - .env
    networks:
      immich:
      traefik:
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.immich.rule=Host(`immich.${DOMAIN}`)
      - traefik.http.routers.immich.entrypoints=websecure
      - traefik.http.routers.immich.service=immich
#      - traefik.http.routers.immich-pub.rule=Host(`immich.${DOMAIN}`)
#      - traefik.http.routers.immich-pub.entrypoints=websecure-pub
      # TODO: add header auth middleware for pub router#
#      - traefik.http.routers.immich-pub.service=immich
      - traefik.http.services.immich.loadbalancer.server.port=2283
    user: 568:568
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true

  redis:
    image: valkey/valkey:9.0.1-alpine@sha256:c106a0c03bcb23cbdf9febe693114cb7800646b11ca8b303aee7409de005faa8
    container_name: immich_redis
    networks:
      immich:
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
    security_opt:
      - no-new-privileges:true

networks:
  immich:
    external: false
    name: immich
  traefik:
    external: true
    name: traefik

volumes:
  model-cache:
