sonarr:
  instance1:
    base_url: http://media:8989
    api_key: !env SONARR_API_KEY

    quality_definition:
      type: series

    media_naming:
      series: default
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    include:
      - template: 0dd5f085ed61a1e01f6d347779dfa1bc # [German] HD Remux + WEB
        source: TRASH

      - template: dca7e5e9e99c703bcbdaaa471dd40e98 # [German] HD Bluray + WEB
        source: TRASH

radarr: 
  instance1:
    base_url: http://media:7878
    api_key: !env RADARR_API_KEY

    media_naming:
      folder: default
      movie:
        rename: true
        standard: standard

    quality_definition:
      type: movie

    include:
      - template: c13c33fdd2c306266b34cb9946de5919 # [German] HD Remux + WEB
        source: TRASH

      - template: 2b90e905c99490edc7c7a5787443748b # [German] HD Bluray + WEB
        source: TRASH
