sonarr:
  instance1:
    base_url: http://media:8989
    api_key: !env SONARR_API_KEY

    quality_definition:
      type: series

    media_naming:
      series: default
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    include:
      - template: 0dd5f085ed61a1e01f6d347779dfa1bc # [German] HD Remux + WEB
        source: TRASH

      - template: dca7e5e9e99c703bcbdaaa471dd40e98 # [German] HD Bluray + WEB
        source: TRASH

radarr: 
  instance1:
    base_url: http://media:7878
    api_key: !env RADARR_API_KEY

    media_naming:
      folder: default
      movie:
        rename: true
        standard: standard

    quality_definition:
      type: movie

    quality_profiles:
      - name: '[GERMAN] FHD Remux, Bluray, WEB'
        reset_unmatched_scores:
          enabled: true
        score_set: german
        upgrade:
          allowed: true
          until_quality: Merged QPs
          until_score: 35000
          min_format_score: 1
        min_format_score: 0
        quality_sort: top
        qualities:
          - name: Merged QPs
            qualities:
              - Remux-1080p
              - Bluray-1080p
              - WEBDL-1080p
              - WEBRip-1080p

    custom_formats:
      - trash_ids:
          # German Audio
          - 86bc3115eb4e9873ac96904a4a68e19e # German
          - 6aad77771dabe9d3e9d7be86f310b867 # German DL (undefined)
          - f845be10da4f442654c13e1f2c3d6cd5 # German DL
          - 4eadb75fb23d09dfc0a8e3f687e72287 # Not German or English

          # German HQ Release Groups
          - 8608a2ed20c636b8a62de108e9147713 # German Remux Tier 01
          - f9cf598d55ce532d63596b060a6db9ee # German Remux Tier 02
          - 54795711b78ea87e56127928c423689b # German Bluray Tier 01
          - 1bfc773c53283d47c68e535811da30b7 # German Bluray Tier 02
          - aee01d40cd1bf4bcded81ee62f0f3659 # German Bluray Tier 03
          - a2ab25194f463f057a5559c03c84a3df # German Web Tier 01
          - 08d120d5a003ec4954b5b255c0691d79 # German Web Tier 02
          - 439f9d71becaed589058ec949e037ff3 # German Web Tier 03
          - 2d136d4e33082fe573d06b1f237c40dd # German Scene

          # German Unwanted
          - 263943bc5d99550c68aad0c4278ba1c7 # German LQ
          - 03c430f326f10a27a9739b8bc83c30e4 # German Microsized
          - a826ee9e46607bc61795c85a6f2b1279 # German LQ (Release Title)

          # Resolution
          - 3bc8df3a71baaac60a31ef696ea72d36 # German 1080p Booster

          # HQ Release Groups
          - 3a3ff47579026e76d6504ebea39390de # Remux Tier 01
          - 9f98181fe5a3fbeb0cc29340da2a468a # Remux Tier 02
          - 8baaf0b3142bf4d94c42a724f034e27a # Remux Tier 03
          - ed27ebfef2f323e964fb1f61391bcb35 # HD Bluray Tier 01
          - c20c8647f2746a1f4c4262b0fbbeeeae # HD Bluray Tier 02
          - 5608c71bcebba0a5e666223bae8c9227 # HD Bluray Tier 03
          - c20f169ef63c5f40c2def54abaf4438e # WEB Tier 01
          - 403816d65392c79236dcb6dd591aeda4 # WEB Tier 02
          - af94e0fe497124d1f9ce732069ec8c3b # WEB Tier 03

          # Misc
          - e7718d7a3ce595f289bfee26adc178f5 # Repack/Proper
          - ae43b294509409a6a13919dedd4764c4 # Repack2
          - 5caaaa1c08c1742aa4342d8c4cc463f2 # Repack3

          # Unwanted
          - ed38b889b31be83fda192888e2286d83 # BR-DISK
          - 90a6f9a284dff5103f6346090e6280c8 # LQ
          - e204b80c87be9497a8a6eaff48f72905 # LQ (Release Title)
          - b8cd450cbfa689c0259a01d9e29ba3d6 # 3D
          - bfd8eb01832d646a0a89c4deb46f8564 # Upscaled
          - 0a3f082873eb454bde444150b70253cc # Extras
          - cae4ca30163749b891686f95532519bd # AV1
          - c465ccc73923871b3eb1802042331306 # Line/Mic Dubbed

          # Audio
          - 2f22d89048b01681dde8afe203bf2e95 # DTS X
          - 3cafb66171b47f226146a0770576870f # TrueHD
          - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
          - a570d4a0e56a2874b64e5bfa55202a1b # FLAC
          - e7c2fcae07cbada050a0af3357491d7b # PCM
          - 8e109e50e0a0b83a5098b056e13bf6db # DTS-HD HRA
          - 185f1dd7264c4562b9022d963ac37424 # DD+
          - f9f847ac70a0af62ea4a08280b859636 # DTS-ES
          - 1c1a4c5e823891c75bc50380a6866f73 # DTS
          - 240770601cc226190c367ef59aba7463 # AAC
          - c2998bd0d90ed5621d8df281e839436e # DD
        assign_scores_to:
          - name: '[GERMAN] FHD Remux, Bluray, WEB'

      - trash_ids:
          - e6886871085226c3da1830830146846c # Generated Dynamic HDR
          - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
        assign_scores_to:
          - name: '[GERMAN] FHD Remux, Bluray, WEB'
            score: -10000

      - trash_ids:
          - 496f355514737f7d83bf7aa4d24f8169 # TrueHD ATMOS
          - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
          - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
        assign_scores_to:
          - name: '[GERMAN] FHD Remux, Bluray, WEB'
            score: -3000

    custom_format_groups:
      - trash_guide:
        - id: d9cc9a504e5ede6294c8b973aad4f028 # [Streaming Services] General
        assign_scores_to:
            - name: '[GERMAN] FHD Remux, Bluray, WEB'