---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk:
      - /
      - /mnt/tank

- search:
    provider: google
    target: _blank
